import express from 'express';
import * as albumController from '../controller/albumController';
import * as middleware from '../middleware/authMiddleware';
import * as upload from '../middleware/uploadFile';
const albumRouter = express.Router();
albumRouter.post('/create/:singerId', middleware.authSingerMiddleware, upload.uploadImage, albumController.createAlbum);
albumRouter.patch('/update/:id', upload.uploadImage, albumController.updateAlbum);
albumRouter.get('/get-detail/:id', albumController.getDetailAlbum);
albumRouter.get('/get-all/album-singers', albumController.getAllAlbumSinger);
albumRouter.get('/get-all', albumController.getAllAlbum);
albumRouter.patch('/update-trash', albumController.updateTrashAlbums);
albumRouter.delete('/delete', albumController.deleteManyAlbums);
albumRouter.get('/get-album-hot', albumController.getAlbumHot);
albumRouter.get('/check-favorite', albumController.checkFavarite);
albumRouter.get('/get-by-singer', albumController.getAlbumBySinger);
albumRouter.get('/get-favorite-album/:id', middleware.authUserMiddleware, albumController.getAlbumFavorite);
export default albumRouter;
