import express from 'express';
import * as songController from '../controller/songController';
import * as middleware from '../middleware/authMiddleware';
import * as upload from '../middleware/uploadFile';
const songRouter = express.Router();
songRouter.post('/create', upload.uploadManyFiles, songController.createSong);
songRouter.get('/get-detail/:id', songController.getDetailSong);
songRouter.get('/get-all', songController.getAllSong);
songRouter.patch('/update/:id', upload.uploadManyFiles, songController.updateSong);
songRouter.patch('/update-trash', middleware.authManySingerMiddleware, songController.updateTrashSong);
songRouter.delete('/delete', songController.deleteManySong);
songRouter.patch('/count/:id', songController.updateViewSong);
songRouter.get('/get-by-album/:id', songController.getSongByAlbumId);
songRouter.get('/check-favorite', songController.checkFavarite);
songRouter.get('/get-new-songs', songController.getTopNewSongs);
songRouter.get('/get-favorite-song/:id', middleware.authUserMiddleware, songController.getSongFavorite);
songRouter.get('/get-same/:id', songController.getSameSongs);
export default songRouter;
